### ISSUE TITLE
立一个 flag，当 star 数到 200 时，发起一次在线的讨论会

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/remote-jobs-in-china#11]
对该在线讨论有兴趣的，请在下面留言或者添加👍的表情

**Comment by claviering** [comment]
你币有了

**Comment by CarlisleCullen** [comment]
吉时已到

**Comment by claviering** [comment]
吉时已到

**Comment by LinuxSuRen** [comment]
感谢各位的支持和关注！请大家及时下载、调试好[飞书](https://www.feishu.cn/)！

会议主题：remote 工作闲聊
会议时间：2月12日 (明天) 10:00 - 11:00 (GMT+8)
会议 ID：850 118 026
会议链接：https://vc.feishu.cn/j/850118026

我们没有具体的议程分享，大家随意聊天。

**Comment by LinuxSuRen** [comment]
会议开始后 15 分钟内没有人进入，取消本次会议！

另立一个 flag https://github.com/LinuxSuRen/remote-jobs-in-china/issues/18
