### ISSUE TITLE
立一个 flag，当 star 数到 500 时，发起一次在线的讨论会

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/remote-jobs-in-china#18]
对该在线讨论有兴趣的，请在下面留言或者添加👍的表情

**Comment by jinx2018** [comment]
资瓷！

**Comment by SAMZONG** [comment]
+me

**Comment by SuperBruceJia** [comment]
+1

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/170649561-0d4904c2-341d-48e0-bf18-028050b8acdd.png)

**Comment by LinuxSuRen** [comment]
欢迎感兴趣的朋友留言你希望听到、交流 ，也欢迎连麦！

预计参与的嘉宾有： @majinghe @tisonkun @danielfbm

**Comment by LinuxSuRen** [comment]
建议的话题：
* 聊一聊怎么加入remote团队（小雅）

**Comment by supermario1990** [comment]
👍

**Comment by LinuxSuRen** [comment]
推荐工具：
* https://www.getclockwise.com/
* 日历
* https://www.donut.com/

**Comment by wey-gu** [comment]
- https://nohello.net/
- https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by LinuxSuRen** [comment]
<img width="1012" alt="debbe4014ba59d02f93c95d0a36d31f" src="https://user-images.githubusercontent.com/1450685/172001347-077617d5-ad0f-4faf-a562-6b77f1e0a06f.png">

**Comment by FeynmanZhou** [comment]
工作事项与协作管理软件
- 工作项管理：[Microsoft To Do](https://todo.microsoft.com/)
- [邮件与日程表](https://outlook.live.com/)

居家办公环境改善
- [米乔腰靠](https://item.jd.com/100023176090.html)
- [乐歌升降台 (M9M)](https://item.jd.com/8057884.html)

工作效率提升小工具
- [WEAVA（网页 & PDF 阅读笔记标注工具）](https://www.weavatools.com/)
- [Grammarly （英文书写自动检查）](grammarly.com)

**Comment by LinuxSuRen** [comment]
活动结束，感谢各位的关注和支持！

**Comment by claviering** [comment]
有微信群？不拉一下？

**Comment by LinuxSuRen** [comment]
直播里提到的微信群，是收集这次直播用的临时微信群，不会长期维护。
