### ISSUE TITLE
圆领是一个提供远程工作的平台，自身提供的岗位很少

### ISSUE THREAD

**Issue by claviering** [LinuxSuRen/remote-jobs-in-china#24]
[圆领](https://www.yuanling.com/)

<img width="696" alt="image" src="https://user-images.githubusercontent.com/16227832/166854707-c43018e8-aab2-46dc-ab45-6e1193953481.png">

**Comment by LinuxSuRen** [comment]
感谢反馈，不过，他们公司确实是全员 remote 的。

**Comment by LinuxSuRen** [comment]
如果没有疑问的话，我就先关闭这个 issue 了哈。欢迎随时打开继续讨论，如果需要的话。
