### ISSUE TITLE
立一个 flag，当 star 数到 1000 时，发起一次直播讨论会

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/remote-jobs-in-china#37]
对该在线讨论有兴趣的，请在下面留言或者添加👍的表情（可以关注我的视频号）

<img src="https://user-images.githubusercontent.com/1450685/172031054-51101abb-9e5c-4926-94c2-22bee365ce71.jpg" width="300px"></img>

上次活动 https://github.com/LinuxSuRen/remote-jobs-in-china/issues/18

**Comment by LinuxSuRen** [comment]
以下是来自小冰的建议：

* 远程办公会有考勤吗？怎么休假？
* 远程办公效率如何？什么样的公司，什么样的岗位，什么样的人会适合远程办公？
* 远程办公的团队需要线下见面吗？以怎样的频率线下聚会比较好

以下是来自小马哥的建议：
* 远程办公能摸鱼吗？
* 远程办公真的能提升效率吗？
* 远程办公如何解决单身问题？
* 远程办公如何解决一日三餐？

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/172543248-869eb843-4589-4e20-aa03-187cd53a4f8d.png)

**Comment by LinuxSuRen** [comment]
![直播预告二维码](https://user-images.githubusercontent.com/1450685/172543288-9dd1ddb2-4cd9-4cdd-8384-592bf87a5503.png)

**Comment by claviering** [comment]
star 涨得这么快的？？

**Comment by LinuxSuRen** [comment]
> star 涨得这么快的？？

我也很好奇

**Comment by yihong0618** [comment]
@LinuxSuRen 
1. 上了 trending
2. 应该是有人宣传了，猜测是微博
3. 你在 insight -> traffic 里能看到大部分来源能推理出大家怎么发现的

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/15976103/172809535-6441a26f-b331-4178-9ad9-01a730fda927.png">

**Comment by lkangjing** [comment]
👍

**Comment by LinuxSuRen** [comment]
数据有点惊人，没太看懂流量都从哪里来的。不过，希望直播能对得起大家的关注。

![image](https://user-images.githubusercontent.com/1450685/172812456-d977d183-fd5f-4cb0-8fd9-a5684dc36720.png)

**Comment by tisonkun** [comment]
> 没太看懂流量都从哪里来的

这就是有人直接贴链接了。

**Comment by LinuxSuRen** [comment]
> 这就是有人直接贴链接了。

嗯，大家开始更多地关注 remote，也许会是一个好事情

**Comment by huadong1989** [comment]
有国外的一些远程办公的公司吗？

**Comment by nshen** [comment]
> > 这就是有人直接贴链接了。
> 
> 嗯，大家开始更多地关注 remote，也许会是一个好事情

僧多粥少怎么会是好事情

**Comment by LinuxSuRen** [comment]
> 僧多粥少怎么会是好事情

从“有需求就会有市场”的角度来说，确实是个好事情

**Comment by LinuxSuRen** [comment]
> 有国外的一些远程办公的公司吗？

我后续会把知道的公司列上去，也欢迎大家一起维护

**Comment by azusachino** [comment]
关注一波

**Comment by majinghe** [comment]
再立个 flag 吧，当 star 达到 3000 的时候，邀请这些 Remote 的公司做一个 meetup 之类的活动，给大家分享一下远程办公的一些实践（工具的使用、沟通的方式、团队凝聚力构建等），其实每个公司都有自己的一些经验，可以相互借鉴，互相学习一下，坚持 Remote 下去

**Comment by LinuxSuRen** [comment]
搞 Meetup 很好啊，不过得有大家的支持了。比如 @majinghe 极狐？@tuhaihe StreamNative？另外，还需要策划下 Meetup 形式，光是演讲有点无趣，能来个沙盘就更酷了。

**Comment by majinghe** [comment]
> 搞 Meetup 很好啊，不过得有大家的支持了。比如 @majinghe 极狐？@tuhaihe StreamNative？另外，还需要策划下 Meetup 形式，光是演讲有点无趣，能来个沙盘就更酷了。

极狐(GitLab)这边我会寻找资源，小规模活动，可以提供场地，大家畅聊远程办公。

**Comment by LinuxSuRen** [comment]
感谢各位的关注，直播结束啦！
