### ISSUE TITLE
关于欧科云链信息的补充

### ISSUE THREAD

**Issue by OctopusLian** [LinuxSuRen/remote-jobs-in-china#40]
去年面试过这个公司，英文名应该叫`OKLink`，远程办公，一个月要来北京出差1次，薪资对标北京，社保公积金缴纳在你远程办公的城市。

**Comment by claviering** [comment]
> 一个月要来北京出差1次

来回机票不便宜吧，加上疫情，来回先隔离7+14🤣

**Comment by LinuxSuRen** [comment]
我暂时关闭这个 issue 了， 大家可以直接补充信息到对应的 YAML 文件中
