### ISSUE TITLE
APISix 的公司名是 API7

### ISSUE THREAD

**Issue by skyzh** [LinuxSuRen/remote-jobs-in-china#5]
Apache APISIX 是他们的产品名称，公司名字叫 API7 或者支流科技。https://www.apiseven.com/en

**Comment by skyzh** [comment]
btw, API7 可以 remote 的来源是？

**Comment by LinuxSuRen** [comment]
> Apache APISIX 是他们的产品名称，公司名字叫 API7 或者支流科技。https://www.apiseven.com/en

感谢指出有误的地方，有兴趣的话可以帮忙修改下。谢谢！

> btw, API7 可以 remote 的来源是？

这里有一个播客提到了 https://www.ximalaya.com/gerenchengzhang/52069269/462104090

**Comment by moonming** [comment]
> btw, API7 可以 remote 的来源是？

你好，我是 API7.ai 的联合创始人和CEO，我们的职位都支持远程，感谢关注
